# Generated by Django 3.1 on 2021-06-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fweanapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='geographical_image',
            field=models.ImageField(upload_to='geographical'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='goal',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='goal_icon',
            field=models.ImageField(upload_to='organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='introduction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='organization',
            name='mission',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='mission_icon',
            field=models.ImageField(upload_to='organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='profile_image',
            field=models.ImageField(upload_to='organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='vision',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='vision_icon',
            field=models.ImageField(upload_to='organization'),
        ),
    ]
