# Generated by Django 3.1 on 2021-06-08 06:39

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fweanapp', '0002_auto_20210608_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagealbum',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.AlterField(
            model_name='programmes',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fweanapp.donors'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_id',
            field=models.CharField(max_length=500),
        ),
    ]
