# Generated by Django 3.1 on 2021-06-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fweanapp', '0011_successstories_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomments',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
