# Generated by Django 2.1 on 2021-07-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fweanapp', '0013_donors_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
