# Generated by Django 2.1 on 2021-07-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fweanapp', '0015_membershipcontents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipcontents',
            name='description',
            field=models.TextField(),
        ),
    ]
