# Generated by Django 2.1 on 2021-07-09 05:33

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fweanapp', '0016_auto_20210709_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipcontents',
            name='description',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
