# Generated by Django 2.1 on 2021-10-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fweanapp', '0018_auto_20210920_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
