# Generated by Django 2.1 on 2021-10-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fweanapp', '0019_auto_20211003_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstories',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
