# Generated by Django 2.1 on 2021-10-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fweanapp', '0020_successstories_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='download_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
