# Generated by Django 2.1 on 2021-10-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fweanapp', '0021_publication_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='district_reached',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='no_of_members',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='no_project_accomplished',
            field=models.IntegerField(default=0),
        ),
    ]
