# Generated by Django 2.1 on 2021-12-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fweanapp', '0024_auto_20211202_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmembers',
            name='president_image',
            field=models.ImageField(upload_to='Board Members'),
        ),
    ]
