# Generated by Django 2.1 on 2021-12-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fweanapp', '0025_auto_20211202_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardexecutivemembers',
            name='executive_member_image',
            field=models.ImageField(upload_to='BoardMembers'),
        ),
        migrations.AlterField(
            model_name='boardimmediatepastpresident',
            name='immediate_past_president_image',
            field=models.ImageField(upload_to='BoardMembers'),
        ),
        migrations.AlterField(
            model_name='boardmembers',
            name='general_secretary_image',
            field=models.ImageField(upload_to='BoardMembers'),
        ),
        migrations.AlterField(
            model_name='boardmembers',
            name='president_image',
            field=models.ImageField(upload_to='BoardMembers'),
        ),
        migrations.AlterField(
            model_name='boardmembers',
            name='secretary_image',
            field=models.ImageField(upload_to='BoardMembers'),
        ),
        migrations.AlterField(
            model_name='boardmembers',
            name='treasurer_image',
            field=models.ImageField(upload_to='BoardMembers'),
        ),
        migrations.AlterField(
            model_name='boardvicepresidents',
            name='vice_president_image',
            field=models.ImageField(upload_to='BoardMembers'),
        ),
    ]
