# Generated by Django 2.1 on 2021-12-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fweanapp', '0026_auto_20211202_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='company_phone_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='current_assets',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='mobile_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='pan_vat',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='membership',
            name='yearly_turnover',
            field=models.CharField(max_length=20),
        ),
    ]
