# Generated by Django 2.1 on 2021-12-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fweanapp', '0027_auto_20211206_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='correspondence_to_reach',
            field=models.CharField(blank=True, choices=[('Residence', 'Residence'), ('Office', 'Office')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='educational_qualification',
            field=models.CharField(blank=True, choices=[('Graduate', 'Graduate'), ('Post Graduate', 'Post Graduate'), ('Professional', 'Professional')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='enterprise_type',
            field=models.CharField(blank=True, choices=[('Manufacturing', 'Manufacturing'), ('Trading', 'Trading'), ('Agriculture', 'Agriculture'), ('Service', 'Service')], max_length=100, null=True),
        ),
    ]
