# Generated by Django 2.1 on 2022-07-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fweanapp', '0028_auto_20211215_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('day', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
